/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef chord_CONSTANTS_H
#define chord_CONSTANTS_H

#include "chord_types.h"

namespace chorddb { namespace middleware {

class chordConstants {
 public:
  chordConstants();

};

extern const chordConstants g_chord_constants;

}} // namespace

#endif
