/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "chord_constants.h"

namespace chorddb { namespace middleware {

const chordConstants g_chord_constants;

chordConstants::chordConstants() {
}

}} // namespace

