/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef datastore_CONSTANTS_H
#define datastore_CONSTANTS_H

#include "datastore_types.h"

namespace chorddb { namespace datastore {

class datastoreConstants {
 public:
  datastoreConstants();

};

extern const datastoreConstants g_datastore_constants;

}} // namespace

#endif
