/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "datastore_constants.h"

namespace chorddb { namespace datastore {

const datastoreConstants g_datastore_constants;

datastoreConstants::datastoreConstants() {
}

}} // namespace

